# Generated by Django 4.1.7 on 2023-03-18 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='students',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 6, 17, 53, 245638, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 6, 18, 1, 286926, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(default=datetime.datetime(2023, 3, 18, 6, 18, 5, 852247, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
