# Generated by Django 4.1.7 on 2023-03-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_students_student_id_alter_students_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
