# Generated by Django 4.1.7 on 2023-03-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
